### PR TITLE
Windows GUI dark mode: avoid an unexpected popup 2

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Due to https://github.com/MediaArea/MediaInfo/pull/851#issuecomment-2141248535

### CODE REVIEW

**Comment by cjee21** [comment]
@JeromeMartinez turns out the new PR that I'm going to make (soon)addresses the root cause of all the dark mode switching bugs. This and #851 is no longer needed with the new PR.

**Comment by JeromeMartinez** [comment]
> This and https://github.com/MediaArea/MediaInfo/pull/851 is no longer needed with the new PR.

We do a release today with them as a workaround, we don't want to block the release but it will be in the next one.

> turns out the new PR that I'm going to make (soon) addresses the root cause of all the dark mode switching bugs. 

It would be great! I thought it was a limitation of C++ Builder but maybe it is not :).
Thank ou for taking care of that.

**Comment by cjee21** [comment]
I can make it within an hour if you want to wait.

**Comment by JeromeMartinez** [comment]
> I can make it within an hour if you want to wait.

OK, we wait a bit.

**Comment by cjee21** [comment]
Done. I make a PR for this main issue first and will look at whether it's possible for HTML view to have dark mode for future release.

**Comment by JeromeMartinez** [comment]
> [...] and will look at whether it's possible for HTML view to have dark mode for future release.

Your help is appreciated!

**Pull request merged**
