### PR TITLE
AutoBuild suite

### PR DESCRIPTION
**Pull request by sgscaffidi3**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Thank you for the suggestion.
But please squash all commits in 1 + rebase so we have only one commit in our changelog.

**Comment by sgscaffidi3** [comment]
Hi Jerome,

Thanks for taking interest in my suggestion.  Thanks for your work on this cool project, too.  I would be happy to squash all these commits for you, but I am not so experienced with Git as to know the best way to go about doing that.  I started Googling it, and it seems like GitHub should offer this feature to the repository maintainer : https://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request

But, I want to know how to do it manually, anyway....  Would you mind instructing me on how to manually squash the commits, since I am still learning Git?

By the way, these changes alone have not solved my problem...  I'm still faced with some build problems.  The MediaInfo build complains that it can't find the MediaInfoLib "configuration"...

In case you are interested, I've included the output from Media-Autobuild_suite below...:

I'm not sure what to think about the zstd message... I thought it was installed, but there is no zstd.pc in /local64/lib/pkgconfig.

Do I need to clone "zstd" and add it to the meadia-autobuild_suite scripts?

libzen git  .............................................. [Already built]
libmediainfo git  ........................................ [Already built]
  Running git update for mediainfo...
┌ mediainfo git  ......................................... [Files missing]
Package zstd was not found in the pkg-config search path.
Perhaps you should add the directory containing `zstd.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zstd', required by 'libcurl', not found
Package zstd was not found in the pkg-config search path.
Perhaps you should add the directory containing `zstd.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zstd', required by 'libcurl', not found
├ Running autogen...
/build/mediainfo-git/Project/GNU/CLI
├ Running configure...
Likely error (tail of the failed operation logfile):
checking whether the ccache g++ linker (D:/mabs/media-autobuild_suite/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking for ccache g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if ccache g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if ccache g++ static flag -static works... yes
checking if ccache g++ supports -c -o file.o... yes
checking if ccache g++ supports -c -o file.o... (cached) yes
checking whether the ccache g++ linker (D:/mabs/media-autobuild_suite/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
configure: error: libmediainfo configuration is not found
configure failed. Check D:/mabs/media-autobuild_suite/build/mediainfo-git/Project/GNU/CLI/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach D:\mabs\media-autobuild_suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

**Comment by JeromeMartinez** [comment]
> Would you mind instructing me on how to manually squash the commits, since I am still learning Git?

I am lazy and use a graphical interface, no idea on Linux command line, something like https://www.git-tower.com/learn/git/faq/git-squash and then force-push maybe...

> and it seems like GitHub should offer this feature to the repository maintainer

I could but it wouldn't be "verified" (indicated as made by you for sure) anymore. Will do if it stays as it.

>  I'm still faced with some build problems. The MediaInfo build complains that it can't find the MediaInfoLib "configuration"...

You need to install `libmediainfo-dev` or similar from your distro, or have MediaInfoLib dir beside MediaInfo dir.
You can download the "All in one package" from https://mediaarea.net/MediaInfo/Download/Source and launch it.

> Do I need to clone "zstd" and add it to the meadia-autobuild_suite scripts?

It is from libcurl and specific to your environment, no idea.

**Comment by cjee21** [comment]
Since it's just one file... the easy manual way is to backup that file then `git reset` this branch remove all commits. Then restore the file if it is no longer in the working directory and make a new commit. Lastly, force push.

If you want the verified label, set-up commit signing locally or use GitHub Web to make the commit.

**Comment by sgscaffidi3** [comment]
I followed your suggestions, @cjee21.  Thanks for your help!  Does it look alright now?  I did it on my master branch, and then noticed that GitHub said to use the ab-suite branch, so I checked-out that branch too and repeated the same steps.  Seems like that wasn't necessary, though...?

**Comment by JeromeMartinez** [comment]
https://github.com/MediaArea/MediaInfo/pull/881/commits is fine.

**Comment by JeromeMartinez** [comment]
@sgscaffidi3 if you don't mind check the other repos for the same issue in order to have all repos with the same style of code.

**Comment by JeromeMartinez** [comment]
> Usually when I make contributions I do it on a new branch and do not touch the main/master branch.

Actually the PR was made on the non master branch so:

> GitHub said to use the ab-suite branch, so I checked-out that branch too and repeated the same steps. Seems like that wasn't necessary, though...?

It was necessary, as the master branch was not used for the PR.

In practice, I don't care for a PR but true it is a good practice to use a branch with a name describing the issue, as it was done there, rather than using the master branch.

**Comment by sgscaffidi3** [comment]
> @sgscaffidi3 if you don't mind check the other repos for the same issue in order to have all repos with the same style of code.

Since I am unemployed at the moment... I might get around to this as I have time.  Unless you want to hire me... then I'll get on it ASAP!

;p

btw, I found an interesting thread as I started researching how to most efficiently perform your request : https://gist.github.com/caniszczyk/3856584

**Comment by cjee21** [comment]
Can use GitHub's search feature: https://github.com/search?q=org%3AMediaArea+%22Exists%29%5C%22+%3D+%5C%22yes%5C%22%22&type=code

**Pull request merged**
