### PR TITLE
Windows GUI: Add online/stub installer

### PR DESCRIPTION
**Pull request by cjee21**
There is still room for improvement/refinement...

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Thank you.
I am thinking to have a stub installer without the version so not rebuilt at each version, and the version would be available online.

**Comment by cjee21** [comment]
> Thank you. I am thinking to have a stub installer without the version so not rebuilt at each version, and the version would be available online.

That is what I am thinking too (like other apps [Firefox?] so users can reuse previously downloaded installer too) but that requires a special URL so I cannot do that now right?

**Comment by JeromeMartinez** [comment]
> but that requires a special URL so I cannot do that now right?

Right. We need to discuss internally about that. I'll let you know.
Also, a stub by version is also good, version is used by some third party websites for specific the possibility to use a specific version, so it would be an addition.

**Comment by cjee21** [comment]
Need find a way to pass language to the 2nd installer if possible. Right now on first time install (not updating) user needs to select language two times and the 2nd installer appears behind the 1st after language selection.

**Comment by cjee21** [comment]
Simplified... less than 90KiB now and no double installer visible :)

**Comment by JeromeMartinez** [comment]
@g-maxime more stuff for the version upgrade script.

**Comment by cjee21** [comment]
> @g-maxime more stuff for the version upgrade script.

and digitally signing another installer exe.

**Comment by cjee21** [comment]
@JeromeMartinez If we want to make the stub installer more secure, we can add a check that the downloaded installer is digitally signed with the correct cert before executing it. It will require third party plugin such as [the one from Mozilla](https://searchfox.org/mozilla-central/source/other-licenses/nsis/Contrib/CertCheck) used by Firefox's stub installer or [another one](https://github.com/past-due/nsisfilecheck).

If the version-less stub is still desired, one possibility is to add a config or ini file containing version and/or URL to the server that can be read by NSIS [ConfigRead](https://nsis.sourceforge.io/ConfigRead) or [ReadINIStr](https://nsis.sourceforge.io/Reference/ReadINIStr) functions.

**Comment by JeromeMartinez** [comment]
> If the version-less stub is still desired, one possibility is to add a config or ini file containing version and/or URL to the server that can be read by NSIS [ConfigRead](https://nsis.sourceforge.io/ConfigRead) or [ReadINIStr](https://nsis.sourceforge.io/Reference/ReadINIStr) functions.

We have already a lot of places with the version, we'll check in the team where the version-less installer should check that.

**Comment by JeromeMartinez** [comment]
> and digitally signing another installer exe.

All is fine now, right?

**Pull request merged**
