### PR TITLE
add EBUCore to help

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Thanks.
Tiny request: next time do a git squash of such commits.

**Comment by retokromer** [comment]
Thanks for the hint. (BTW: I didn't know at all this possibility before Peter's tweet.)

**Comment by JeromeMartinez** [comment]
> (BTW: I didn't know at all this possibility before Peter's tweet.)

There is definitely a lack of documentation about output formats. It is mainly visible in the Windows GUI for the moment (Linux/Mac GUIs in the next version thanks to some feature sponsoring). I take any help proposal for documentation ;-).

You can try some other ["magic" values](https://github.com/MediaArea/MediaInfo/blob/master/Source/GUI/VCL/GUI_Main.cpp#L215-L222).

**Comment by retokromer** [comment]
I will download, and read it during 11 hours flight or so ;-)

**Pull request merged**
