### PR TITLE
fla, shn, aif, aifc and vro

### PR DESCRIPTION
**Pull request by Sami32**
`.fla`
https://xiph.org/flac/documentation_tools_flac.html#usage
https://en.wikipedia.org/wiki/ISO_9660#Limitations

`.aif` and `.aifc`
https://en.wikipedia.org/wiki/Audio_Interchange_File_Format
Sample: [ima4.aifc.txt](https://github.com/MediaArea/MediaInfo/files/2088327/ima4.aifc.txt)

`.vro`
https://fr.wikipedia.org/wiki/Video_Recording_Object_file
Sample: https://www.dropbox.com/s/adl1q8mcvru972b/VR_MOVIE.VRO

`.shn`
https://en.wikipedia.org/wiki/Shorten_(file_format)
Sample: [luckynight.shn.txt](https://github.com/MediaArea/MediaInfo/files/2088336/luckynight.shn.txt)

This PR will have its complement on MediaInfoLib.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
bad .vro link.

**Comment by Sami32** [comment]
Well, it was still valid when i posted an issue here some months ago so i didn't verified. As the file is more than 800 MB i do note liké thé idea of uploading it on my low speed upload connection...

**Comment by JeromeMartinez** [comment]
Sorry being late on the issues. Would you mind upload few MB of the file? I don't need the complete file.

**Comment by Sami32** [comment]
No worry ;)
Well, i finally forced myself to upload it but it will not be available before some hours.
As i thought that you already downloaded this file some months ago i didn't expected to have to.
But as it is also related to an [issue](https://github.com/MediaArea/MediaInfoLib/issues/596) you should have the full file IMO.

**Comment by Sami32** [comment]
http://www.rapidshare.space/zKPtVSm

**Pull request merged**
