### PR TITLE
Windows GUI: Ensure correct installers are used for each system

### PR DESCRIPTION
**Pull request by cjee21**
Since there is now ARM64.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
For coherency, not something similar for i386 (test on i386 only or ARM64 on Win10)?

**Comment by cjee21** [comment]
For combined installer will be in separate PR along with adding ARM64 handling after making sure ARM64 works fine.

**Comment by JeromeMartinez** [comment]
> after making sure ARM64 works fine.

Exactly.

**Comment by cjee21** [comment]
@JeromeMartinez adding ARM64 to combined installer increases size by roughly 3.5MiB (excluding digital signatures). I think it is acceptable. If want to really save bandwidth can use the online installer and only use combined when offline install is needed.

**Pull request merged**
