### PR TITLE
typos and fixes

### PR DESCRIPTION
**Pull request by the-j0k3r**
some obvious typos fixes

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Thanks, appreciated.

Would you mind to change `http://` to `//` (HTTPS version for HTTPS users, HTTP version for HTTP  users) or `https://` (HTTPS version for all) in order to have no use of unencrypted URL for HTTPS users?
Ho, I would actually prefer to use `https://mediaarea.net/MediaInfo/License` instead, I prefer to avoid websites I don't control, when I can.

And as we are changing the Mac part, I suggest to use the preferred Apple form, [macOS](https://en.wikipedia.org/wiki/MacOS);

**Comment by the-j0k3r** [comment]
> Ho, I would actually prefer to use https://mediaarea.net/MediaInfo/License instead, I prefer to avoid websites I don't control, when I can.

I hear you and done. What do you think?

**Comment by JeromeMartinez** [comment]
Perfect, thanks again.
Don't hesitate if you find other typos and fixes.

**Comment by the-j0k3r** [comment]
Depends if you think its worth fixing the odds and ends typos in the `History_CLI.txt` and `History_GUI.txt` documents. at which time it may be worth considering converting those to `markdown` format.

**Comment by the-j0k3r** [comment]
I can surely have a look at the ones you pointed out, if I can be of service and time permitting, you can expect some more contributions.

The README here, generally speaking, could be improved, at the moment though, it satisfies IMHO the basic job it proposes to do, without being hard to understand.

Many hands make light work and many eyes see further.

**Pull request merged**
