### PR TITLE
Windows GUI: Update installers

### PR DESCRIPTION
**Pull request by cjee21**
Add ARM64 to all-in-one installer and update the other scripts for consistent layout.

### CODE REVIEW

**Comment by cjee21** [comment]
@JeromeMartinez adding Windows 11 ARM64 support to combined/all-in-one installer increases size by roughly 3.5MiB (excluding digital signatures). I think it is acceptable. If want to really save bandwidth can use the online installer and only use combined/all-in-one when offline install is needed.

**Comment by JeromeMartinez** [comment]
> adding Windows 11 ARM64 support to combined/all-in-one installer increases size by roughly 3.5MiB (excluding digital signatures). I think it is acceptable. I

I am fine with that.
By the way, the `ARM64_WithoutInstaller.7z` is missing.

**Comment by cjee21** [comment]
> By the way, the `ARM64_WithoutInstaller.7z` is missing.

[This one](https://github.com/MediaArea/MediaInfo/blob/f41892dcd4cbf9a35ced772c8f36d22b8ca56913/Release/Release_GUI_Windows_ARM64.bat)?

**Comment by cjee21** [comment]
> By the way, the `ARM64_WithoutInstaller.7z` is missing.

[This one](https://github.com/MediaArea/MediaInfo/blob/f41892dcd4cbf9a35ced772c8f36d22b8ca56913/Release/Release_GUI_Windows_ARM64.bat)?

🤔 What went wrong? It is called here: https://github.com/MediaArea/MediaArea-Utils/blob/e85a18ff6b5652930b9d6adee471b3213f4bfdd6/build_release/BuildRelease.bat#L333

**Comment by cjee21** [comment]
> By the way, the `ARM64_WithoutInstaller.7z` is missing.

[This one](https://github.com/MediaArea/MediaInfo/blob/f41892dcd4cbf9a35ced772c8f36d22b8ca56913/Release/Release_GUI_Windows_ARM64.bat)?

🤔 What went wrong? It is called [here](https://github.com/MediaArea/MediaArea-Utils/blob/e85a18ff6b5652930b9d6adee471b3213f4bfdd6/build_release/BuildRelease.bat#L333) and copied [here](https://github.com/MediaArea/MediaArea-Utils/blob/e85a18ff6b5652930b9d6adee471b3213f4bfdd6/build_release/BuildRelease.bat#L383).

I checked my local build and `MediaInfo_GUI_Windows_ARM64_WithoutInstaller.7z` is present with correct files.

**Comment by JeromeMartinez** [comment]
> I checked my local build and MediaInfo_GUI_Windows_ARM64_WithoutInstaller.7z is present with correct files.

I launched a new build, we'll see.

**Comment by g-maxime** [comment]
> > adding Windows 11 ARM64 support to combined/all-in-one installer increases size by roughly 3.5MiB (excluding digital signatures). I think it is acceptable. I
> 
> I am fine with that. By the way, the `ARM64_WithoutInstaller.7z` is missing.

Fixed in the CI now.

**Comment by JeromeMartinez** [comment]
@rednoah please test [this snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241208/MediaInfo_GUI_24.11.20241208_Windows.exe).
This should be our final work on Windows 11 ARM64 support: DLL, CLI including remote (https) file support, hybrid GUI (no need of complete ARM64 support as the slow part is in the DLL and the DLL is native) including explorer extension & tooltip.

**Comment by JeromeMartinez** [comment]
> For DLL maybe can distribute ARM64X too since already building it for the GUI 

I'll discuss about that with the team tomorrow, we have already several packages, but at the least we can indicate to potential users that they can pick the DLL from the the GUI ZIP.

**Comment by rednoah** [comment]
> @rednoah please test [this snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241208/MediaInfo_GUI_24.11.20241208_Windows.exe). This should be our final work on Windows 11 ARM64 support: DLL, CLI including remote (https) file support, hybrid GUI (no need of complete ARM64 support as the slow part is in the DLL and the DLL is native) including explorer extension & tooltip.

Happy to confirm that everything works. GUI starts. Windows Explorer tooltip and context menu works. DLL can be loaded from my tools as well.

**Pull request merged**
