### PR TITLE
Windows GUI: Use older API for getting system DPI, update

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
For an unknown reason the binary is trying to load the function even if the function is not called, this was not expected, usually the crash happens only when the function is called, so we remove it completely as an hotfix for the release.

**Comment by cjee21** [comment]
> For an unknown reason the binary is trying to load the function even if the function is not called, this was not expected

Is the version check working properly? If it is then I wonder if this has anything to do with speculative execution.

**Comment by cjee21** [comment]
> For an unknown reason the binary is trying to load the function even if the function is not called, this was not expected

Looks like it is looking for `GetSystemDpiForProcess` immediately on start before application code is run. Seems need to use `LoadLibrary` and `GetProcAddress` if we still want to use newer API on newer Windows.

**Comment by cjee21** [comment]
@JeromeMartinez please take a look at #861

**Pull request merged**
