### PR TITLE
Windows GUI: Enable 64-bit version

### PR DESCRIPTION
**Pull request by cjee21**
Screenshot 2024-06-22 180755
Screenshot 2024-06-22 180653

Requires building 64-bit versions of ZenLib and zlib as well. For these two, no changes required other than enabling 64-bit.

Advantages of 64-bit version:
- Better performance?
  - 05 seconds 988 milliseconds vs 09 seconds 258 milliseconds on a single folder test
- Large address aware
- High Entropy VA / High-entropy 64-bit address space layout randomization (ASLR)

Issues that may be related: #575 #788 #868

### CODE REVIEW

**Comment by cjee21** [comment]
Need to clean up the project file and change paths to relative...

**Comment by cjee21** [comment]
Please see the updated first post.

I recommend having 64-bit installer version due to the advantages listed in first post, the fact that most PCs should be 64-bit already and the effect of smaller installed size on 64-bit PCs due to removal of `MediaInfo_i386.dll`.

**Comment by JeromeMartinez** [comment]
Not tested but my understanding is that the 32-bit binaries are no more in the installer, size is smaller so it is good, but the 32-bit related code won't work.
I don't wish to have both architectures in the installer at long term but it could be a good first step for this PR, please update the PR for embedding both architectures, then we'll work on another PR for having a 32-bit only installer and update the main installer for downloading this 32-bit installer when 32-bit is detected.

We'll have to update build scripts in https://github.com/MediaArea/MediaArea-Utils/ , please some patience, it is on our side but we have other things to finish before managing that (including building the GUI twice). It won't be forever but not in June.

Thank you for pushing us in that direction, just that in the cases of EdgeView and 64-bit we are the blockers and we need some time. But don't give up, we are still very happy with you pushing us.

> most PCs should be 64-bit

You can not imagine the count of emails I received when we stop WinXP support despite the fact it was end of life for years, I bet the same for 32-bit, actually even worse (we have no stat, sadly).

**Comment by cjee21** [comment]
> Not tested but my understanding is that the 32-bit binaries are no more in the installer, size is smaller so it is good, but the 32-bit related code won't work. I don't wish to have both architectures in the installer at long term but it could be a good first step for this PR, please update the PR for embedding both architectures, then we'll work on another PR for having a 32-bit only installer and update the main installer for downloading this 32-bit installer when 32-bit is detected.

This PR makes the installer generate a universal one. It will use only 64-bit binaries on 64-bit PCs. For 32-bit PCs should be still the same as now unless I made a mistake somewhere.
On your side you just need to make sure to build 64-bit versions of ZenLib, zlib and CURL. Then for MediaInfo, just select 64-bit target and build with the updated project file in this PR.

> we have no stat, sadly

Found outdated stats: https://blogs.windows.com/windowsexperience/2010/07/08/64-bit-momentum-surges-with-windows-7/

**Comment by JeromeMartinez** [comment]
> most PCs should be 64-bit

Now I have doubts, looks like [that 32-bit Windows is less than 1%](https://www.pcbenchmarks.net/os-marketshare.html) so I would think to remove it...

**Comment by cjee21** [comment]
> > most PCs should be 64-bit
> 
> Now I have doubts, looks like [that 32-bit Windows is less than 1%](https://www.pcbenchmarks.net/os-marketshare.html) so I would think to remove it...

Well the last time I remember seeing a 32-bit Windows PC was several years ago on a low-end small-sized Intel tablet.

**Comment by JeromeMartinez** [comment]
>  unless I made a mistake somewhere.

I have read it again and it seems that my first read was wrong.

> On your side you just need to make sure to build 64-bit versions of ZenLib, zlib and CURL. Then for MediaInfo, just select 64-bit target and build with the updated project file in this PR.

We need to find where it is in our scripts and add the right line for building the 64-bit version. Theses scripts are very old so we need to read and understand them again :-D.

**Comment by cjee21** [comment]
> We need to find where it is in our scripts and add the right line for building the 64-bit version. Theses scripts are very old so we need to read and understand them again :-D.

Where I think it is after a quick look: https://github.com/MediaArea/MediaArea-Utils/blob/master/build_release/BuildRelease.bat#L285

**Comment by cjee21** [comment]
> > most PCs should be 64-bit
> 
> Now I have doubts, looks like [that 32-bit Windows is less than 1%](https://www.pcbenchmarks.net/os-marketshare.html) so I would think to remove it...

Less than 0.1% if we look at the 64 vs 32 chart. That link also shows Windows 7 is less than 0.5% in the versions chart.

Here is another source of stats: https://store.steampowered.com/hwsurvey

If we assume these stats accurately represent the actual user base and also assume that all unlisted versions are 32-bit, then the percentage of 32-bit Windows will be around 3%.

Side note: take a look at the Windows 11 share in both sources... it's time for Windows 11 explorer context menu 😉

**Comment by cjee21** [comment]
Corrected path for x64 CURL since I just saw its location in the repos.

> we'll work on another PR for having a 32-bit only installer 

Added as an additional commit.

> update the main installer for downloading this 32-bit installer when 32-bit is detected.

This one leave it up to your team since need server URL and I'm not good enough with NSIS to do this.

From another page:
> Package size is a hot topic for us, most people don't care at all and download GB of content but some others complain loudly when there is 1 more MB in the main package...

Then you might want to update your 8-year old 7-Zip that I came across at https://github.com/MediaArea/MediaArea-Utils-Binaries/tree/master/Windows/7-Zip. I tried compressing the extracted 7z dev snapshot with my latest 7-Zip using the same command line as your script and it resulted in a slightly smaller file size.

**Comment by cjee21** [comment]
Improved the installer.

The first change is adding back the option to run MediaInfo after installation has completed. I saw that it was removed "because it is run in admin privileges". It is now run at user privileges.

The second change is regarding this:

> @JeromeMartinez Might want to add check to see if MediaInfo is running during uninstall or add `/REBOOTOK` switch as currently it appears to complete uninstall but leave behind MediaInfo.exe and the DLL if MediaInfo is running during uninstall.

Now if MediaInfo is running or something is using `MediaInfo.dll` during uninstall, it will now move the in-use files to `%TEMP%` and schedule them for deletion on next reboot. It will then ask if the user want to reboot immediately or later on completion. The `Program Files\MediaInfo` folder will be removed cleanly unless there is still something there. If the user defers reboot and re-installs MediaInfo, the new installation will not be affected after reboot since the old files that are scheduled for deletion has been moved/renamed.

If MediaInfo is not running and nothing is using `MediaInfo.dll` during uninstall, there is no change in behaviour. The `Program Files\MediaInfo` folder will be removed cleanly unless there is still something there. There will be no reboot prompt.

This is implemented using macros from `Library.nsh`. The macros can possibly be used to handle installation of all exe and dlls and registration/unregistration/removal of `MediaInfo_InfoTip.dll` as well but I did not attempt this to keep changes to a minimal to avoid breaking something.

**Comment by cjee21** [comment]
Add 64-bit only installer.

Size comparison:

```
MediaInfo\Release>dir | find "MediaInfo_GUI"
27/06/2024  11:20 AM         9,887,983 MediaInfo_GUI_24.05_Windows.exe
27/06/2024  11:20 AM         4,973,713 MediaInfo_GUI_24.05_Windows_i386.exe
27/06/2024  11:20 AM         5,521,995 MediaInfo_GUI_24.05_Windows_x64.exe
```

Maybe can do something like this if want to minimize download size:
https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/StubInstaller.html

**Comment by cjee21** [comment]
Re-based on 24.06 while ensuring version numbers in project file are updated. Also reduced number of commits and moved an unrelated commit to another branch where that file was changed over there.

**Comment by JeromeMartinez** [comment]
> Maybe can do something like this if want to minimize download size:

The Stub installer is also something we are thinking to add while changing to a 64-bit offer so we show 1 small installer only to all download websites without issue with 32-bit machines (there may actually be more than estimated in the wild).

**Comment by cjee21** [comment]
Rebased and changed 24.05 to 24.06 in installer scripts that I missed.

**Comment by JeromeMartinez** [comment]
For reference https://github.com/MediaArea/MediaArea-Utils/pull/297 and https://github.com/MediaArea/MediaInfo/pull/883 were required for having everything ready for our workflow.

**Comment by JeromeMartinez** [comment]
[dev snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240702-4/)

**Comment by cjee21** [comment]
> [dev snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240702-4/)

This build is not from latest master and still has disappearing menu glitch but it's okay, I found a newer dev snapshot. I will use it until the next version to enjoy the new changes and also as additional testing.

Might want to update the project files for ZenLib and zlib to add 64-bit targets so that people who use IDE to build will not have trouble. They can easily manually add the target themselves though. I didn't expect building from CLI to work without 64-bit target in project file but it does.

**Comment by cjee21** [comment]
First bug discovered. If open a file from explorer context menu then immediately switch from Basic to Graph view, this pops up:
Screenshot 2024-07-03 120730

If switch to HTML view then to Graph view, it works.

**Pull request merged**
