### PR TITLE
Windows GUI: Quick temp fix for translations after update

### PR DESCRIPTION
**Pull request by cjee21**
Quick temporary fix that should prevent occurrence of bug mentioned at https://github.com/MediaArea/MediaInfo/pull/879#issuecomment-2182628248 after a MediaInfo update that contains updated translations.

### CODE REVIEW

**Comment by cjee21** [comment]
@JeromeMartinez I can help test if you can provide a dev snapshot build with this change.

**Comment by JeromeMartinez** [comment]
[dev snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240621-4/MediaInfo_GUI_24.05.20240621_Windows.exe) and also the [one without installer](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20240621-4/MediaInfo_GUI_24.05.20240621_Windows_x64_WithoutInstaller.7z) needs to have no problem.

@cjee21 your help is very appreciated.

**Comment by cjee21** [comment]
**Test 1**
1. Uninstall MediaInfo and clean-up all traces of it from %APPDATA%
2. Install MediaInfo_GUI_24.05.1_Windows
3. Run it a few times and check translations
4. Install MediaInfo_GUI_24.05.20240621_Windows as an update
5. Run it a few times and check translations

Result: pass

**Test 2**
1. Uninstall MediaInfo and clean-up all traces of it from %APPDATA%
2. Install MediaInfo_GUI_24.05.20240621_Windows
3. Run it a few times and check translations

Result: pass

**Test 3**
1. Uninstall MediaInfo and clean-up all traces of it from %APPDATA%
4. Run MediaInfo_GUI_24.05.20240621_Windows_x64_WithoutInstaller\MediaInfo.exe a few times and check translations
5. Check that no %APPDATA%\MediaInfo\... is created

Result: pass

**Comment by JeromeMartinez** [comment]
> Result: pass

Thank you!

**Pull request merged**
